
import Link from "next/link"

export const metadata = {
  title: 'Template project',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header className="text-right" style={{
          backgroundColor: "lightblue",
          padding: "1rem",
        }}>
          <Link href={"/About"} className="pr-4">Click to go to About</Link>
          <Link href={"/"}>Click to go to Home</Link>
        </header>
        <div className="text-center font-bold font-segoe text-2xl text-red-600">
          {children}
        </div>

        <footer className="p-4 bg-blue-200">
          <p className="font-segoe text-green-800 text-center">footer</p>
        </footer>
      </body>

    </html>
  )
}
